<?php

namespace Database\Seeders;

use App\Models\Inventory;
use Illuminate\Database\Seeder;

class InventorySeeder extends Seeder
{
    public function run(): void
    {
        $inventoryItems = [
            [
                'item_name' => 'Chicken Breast',
                'item_code' => 'INV-001',
                'category' => 'meat',
                'unit' => 'kg',
                'current_quantity' => 48,
                'minimum_quantity' => 10,
                'maximum_quantity' => 100,
                'unit_cost' => 8.50,
                'total_value' => 48 * 8.50,
                'status' => 'in_stock',
                'supplier_name' => 'Fresh Meat Co.',
                'supplier_contact' => '+1 (555) 100-0001',
                'last_restocked_date' => now()->subDays(5),
                'reorder_quantity' => 50,
                'daily_usage_rate' => 5,
                'days_of_supply' => 10,
            ],
            [
                'item_name' => 'Beef',
                'item_code' => 'INV-002',
                'category' => 'meat',
                'unit' => 'kg',
                'current_quantity' => 28,
                'minimum_quantity' => 15,
                'maximum_quantity' => 80,
                'unit_cost' => 12.75,
                'total_value' => 28 * 12.75,
                'status' => 'in_stock',
                'supplier_name' => 'Premium Beef Suppliers',
                'supplier_contact' => '+1 (555) 100-0002',
                'last_restocked_date' => now()->subDays(7),
                'reorder_quantity' => 40,
                'daily_usage_rate' => 3,
                'days_of_supply' => 9,
            ],
            [
                'item_name' => 'Salmon Fillet',
                'item_code' => 'INV-003',
                'category' => 'meat',
                'unit' => 'kg',
                'current_quantity' => 4,
                'minimum_quantity' => 5,
                'maximum_quantity' => 50,
                'unit_cost' => 18.25,
                'total_value' => 4 * 18.25,
                'status' => 'low_stock',
                'supplier_name' => 'Ocean Fresh Seafood',
                'supplier_contact' => '+1 (555) 100-0003',
                'last_restocked_date' => now()->subDays(3),
                'reorder_quantity' => 25,
                'daily_usage_rate' => 2,
                'days_of_supply' => 2,
            ],
            [
                'item_name' => 'Tomatoes',
                'item_code' => 'INV-004',
                'category' => 'vegetable',
                'unit' => 'kg',
                'current_quantity' => 85,
                'minimum_quantity' => 20,
                'maximum_quantity' => 150,
                'unit_cost' => 2.25,
                'total_value' => 85 * 2.25,
                'status' => 'in_stock',
                'supplier_name' => 'Green Garden Farms',
                'supplier_contact' => '+1 (555) 100-0004',
                'last_restocked_date' => now()->subDays(2),
                'reorder_quantity' => 60,
                'daily_usage_rate' => 10,
                'days_of_supply' => 9,
            ],
            [
                'item_name' => 'Lettuce',
                'item_code' => 'INV-005',
                'category' => 'vegetable',
                'unit' => 'kg',
                'current_quantity' => 12,
                'minimum_quantity' => 15,
                'maximum_quantity' => 80,
                'unit_cost' => 1.75,
                'total_value' => 12 * 1.75,
                'status' => 'low_stock',
                'supplier_name' => 'Fresh Leaf Produce',
                'supplier_contact' => '+1 (555) 100-0005',
                'last_restocked_date' => now()->subDays(1),
                'reorder_quantity' => 40,
                'daily_usage_rate' => 8,
                'days_of_supply' => 2,
            ],
            [
                'item_name' => 'Flour',
                'item_code' => 'INV-006',
                'category' => 'grain',
                'unit' => 'kg',
                'current_quantity' => 180,
                'minimum_quantity' => 50,
                'maximum_quantity' => 300,
                'unit_cost' => 0.85,
                'total_value' => 180 * 0.85,
                'status' => 'in_stock',
                'supplier_name' => 'Baking Supplies Inc.',
                'supplier_contact' => '+1 (555) 100-0006',
                'last_restocked_date' => now()->subDays(14),
                'reorder_quantity' => 100,
                'daily_usage_rate' => 5,
                'days_of_supply' => 36,
            ],
            [
                'item_name' => 'Olive Oil',
                'item_code' => 'INV-007',
                'category' => 'other',
                'unit' => 'l',
                'current_quantity' => 35,
                'minimum_quantity' => 10,
                'maximum_quantity' => 60,
                'unit_cost' => 15.50,
                'total_value' => 35 * 15.50,
                'status' => 'in_stock',
                'supplier_name' => 'Mediterranean Oils',
                'supplier_contact' => '+1 (555) 100-0007',
                'last_restocked_date' => now()->subDays(21),
                'reorder_quantity' => 25,
                'daily_usage_rate' => 1,
                'days_of_supply' => 35,
            ],
            [
                'item_name' => 'Mozzarella Cheese',
                'item_code' => 'INV-008',
                'category' => 'dairy',
                'unit' => 'kg',
                'current_quantity' => 6,
                'minimum_quantity' => 8,
                'maximum_quantity' => 50,
                'unit_cost' => 9.25,
                'total_value' => 6 * 9.25,
                'status' => 'low_stock',
                'supplier_name' => 'Dairy Delight',
                'supplier_contact' => '+1 (555) 100-0008',
                'last_restocked_date' => now()->subDays(2),
                'reorder_quantity' => 20,
                'daily_usage_rate' => 3,
                'days_of_supply' => 2,
            ],
            [
                'item_name' => 'Rice',
                'item_code' => 'INV-009',
                'category' => 'grain',
                'unit' => 'kg',
                'current_quantity' => 140,
                'minimum_quantity' => 30,
                'maximum_quantity' => 200,
                'unit_cost' => 1.25,
                'total_value' => 140 * 1.25,
                'status' => 'in_stock',
                'supplier_name' => 'Asian Grains Co.',
                'supplier_contact' => '+1 (555) 100-0009',
                'last_restocked_date' => now()->subDays(10),
                'reorder_quantity' => 80,
                'daily_usage_rate' => 8,
                'days_of_supply' => 18,
            ],
            [
                'item_name' => 'Coffee Beans',
                'item_code' => 'INV-010',
                'category' => 'beverage',
                'unit' => 'kg',
                'current_quantity' => 3,
                'minimum_quantity' => 5,
                'maximum_quantity' => 40,
                'unit_cost' => 24.99,
                'total_value' => 3 * 24.99,
                'status' => 'low_stock',
                'supplier_name' => 'Premium Coffee Importers',
                'supplier_contact' => '+1 (555) 100-0010',
                'last_restocked_date' => now()->subDays(1),
                'reorder_quantity' => 20,
                'daily_usage_rate' => 2,
                'days_of_supply' => 2,
            ],
        ];

        foreach ($inventoryItems as $item) {
            Inventory::firstOrCreate(
                ['item_code' => $item['item_code']],
                $item
            );
        }
    }
}
